
project_id = "zlfpiovyodiyecdueiig"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.admin-create-user]
verify_jwt = true

[functions.check-retraining]
verify_jwt = false

[functions.admin-update-role]
verify_jwt = true

[functions.get-google-config]
verify_jwt = true

[functions.google-calendar-auth]
verify_jwt = false

[functions.sync-meeting-to-google]
verify_jwt = true

[functions.sync-tasks-to-google]
verify_jwt = true

[functions.import-google-tasks]
verify_jwt = false

[functions.export-tasks-to-google-tasks]
verify_jwt = false

[functions.sync-tasks-bidirectional]
verify_jwt = false

[functions.invalidate-google-calendar-tokens]
verify_jwt = true

[functions.process-calendar-sync-queue]
verify_jwt = false

[functions.send-ticket-notifications]
verify_jwt = true

[functions.send-task-notifications]
verify_jwt = true

[functions.send-inventory-notifications]
verify_jwt = true

[functions.send-checklist-notifications]
verify_jwt = true

[edge_runtime]
enabled = true
port = 54325

[analytics]
enabled = false
