
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlfpiovyodiyecdueiig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsZnBpb3Z5b2RpeWVjZHVlaWlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzA0OTEsImV4cCI6MjA2MDM0NjQ5MX0.GAY6GgcApuuuH9MBXaThy-nW4UciDq2t6iSo6mMGiF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    debug: false // Disable debug to reduce noise
  },
  global: {
    headers: {
      'x-application-name': 'teamtegrate'
    }
  },
  db: {
    schema: 'public'
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});

// Simple auth state logging
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Supabase Auth state change:', event, 'Session:', session ? 'exists' : 'null');
  
  if (event === 'TOKEN_REFRESHED') {
    console.log('Supabase: Token successfully refreshed');
  }
  
  if (event === 'SIGNED_OUT') {
    console.log('Supabase: User signed out');
  }
  
  if (session) {
    console.log('Supabase: User ID:', session.user?.id);
  }
  
  if (event === 'SIGNED_IN') {
    console.log('Supabase: User successfully signed in');
  }
});
